// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PriceServiceClient is the client API for PriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PriceServiceClient interface {
	ReadPrices(ctx context.Context, opts ...grpc.CallOption) (PriceService_ReadPricesClient, error)
}

type priceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceServiceClient(cc grpc.ClientConnInterface) PriceServiceClient {
	return &priceServiceClient{cc}
}

func (c *priceServiceClient) ReadPrices(ctx context.Context, opts ...grpc.CallOption) (PriceService_ReadPricesClient, error) {
	stream, err := c.cc.NewStream(ctx, &PriceService_ServiceDesc.Streams[0], "/proto.PriceService/ReadPrices", opts...)
	if err != nil {
		return nil, err
	}
	x := &priceServiceReadPricesClient{stream}
	return x, nil
}

type PriceService_ReadPricesClient interface {
	Send(*ReadPricesRequest) error
	Recv() (*ReadPricesResponse, error)
	grpc.ClientStream
}

type priceServiceReadPricesClient struct {
	grpc.ClientStream
}

func (x *priceServiceReadPricesClient) Send(m *ReadPricesRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *priceServiceReadPricesClient) Recv() (*ReadPricesResponse, error) {
	m := new(ReadPricesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PriceServiceServer is the server API for PriceService service.
// All implementations must embed UnimplementedPriceServiceServer
// for forward compatibility
type PriceServiceServer interface {
	ReadPrices(PriceService_ReadPricesServer) error
	mustEmbedUnimplementedPriceServiceServer()
}

// UnimplementedPriceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPriceServiceServer struct {
}

func (UnimplementedPriceServiceServer) ReadPrices(PriceService_ReadPricesServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadPrices not implemented")
}
func (UnimplementedPriceServiceServer) mustEmbedUnimplementedPriceServiceServer() {}

// UnsafePriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceServiceServer will
// result in compilation errors.
type UnsafePriceServiceServer interface {
	mustEmbedUnimplementedPriceServiceServer()
}

func RegisterPriceServiceServer(s grpc.ServiceRegistrar, srv PriceServiceServer) {
	s.RegisterService(&PriceService_ServiceDesc, srv)
}

func _PriceService_ReadPrices_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PriceServiceServer).ReadPrices(&priceServiceReadPricesServer{stream})
}

type PriceService_ReadPricesServer interface {
	Send(*ReadPricesResponse) error
	Recv() (*ReadPricesRequest, error)
	grpc.ServerStream
}

type priceServiceReadPricesServer struct {
	grpc.ServerStream
}

func (x *priceServiceReadPricesServer) Send(m *ReadPricesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *priceServiceReadPricesServer) Recv() (*ReadPricesRequest, error) {
	m := new(ReadPricesRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PriceService_ServiceDesc is the grpc.ServiceDesc for PriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PriceService",
	HandlerType: (*PriceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadPrices",
			Handler:       _PriceService_ReadPrices_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "price-service.proto",
}
